name: example-workflow

on: push

jobs:
    demo-job:
        runs-on: ubuntu:latest
        steps:
        - name: Checkout Stage
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo "Hello Welcome"
        
        - name: Test Message
          run: echo "This is testing message"

        - name: Close Message
          run: echo "We're close"
