name: example-workflow

on: push

jobs:
    demo-job:
        runs-on: ubuntu:own
        steps:
        - name: Checkout Stage
          uses: actions/checkout@v4

        - name: Welcome Message
          run: | 
            echo "Hello Welcome"
            echo "This is testing message"
            ls -la
